### ISSUE TITLE
Rename `modal` selector to `dialog`?

### ISSUE THREAD

**Issue by tysongach** [citizensadvice/capybara_accessible_selectors#71]
I wonder if there’s any appetite for renaming the `modal` selector to `dialog`?

My thinking here is…

1. HTML has a native `<dialog>` element that’s been improved and gained broad support amongst the different browsers - it’s not `<modal>`…
2. The [ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) that we link to in the README starts off with “A dialog is a…” - the term ‘modal’ is in the title of that document, but it’s in parenthesis as if its a further explanation and not the thing itself
3. As noted in the README, the selector cannot “…distinguish between a `<dialog>` opened as a modal and as non-modal.”, so it can feel odd to use `within_modal` to drill down into a non-modal `<dialog>`
4. As this [great article from Hidde de Vries](https://hidde.blog/dialog-modal-popover-differences/#heading-3) explains, “modality is more of a characteristic than a component itself.”
5. The [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) also has the concept of modal and non-modal, which further muddies that term from the perspective of what element is being targeted

Would `dialog` be more descriptive of what this selector targets?

**Comment by mrdaniellewis** [comment]
I do like having a specific modal selector, but I agree there should also be a dialog selector.

The current modal selector looks for (translated from xpath to css) `dialog,[role=dialog][aria-modal=true],[role=alertdialog][aria-modal=true]`.  This isn't correct as `dialog` could be a modal or not, so yes, at the moment it isn't specifically selecting modals.

I do mean to correct this as I've now realised there is a `:modal` css pesudo class that can distinguish between them.

**Comment by tysongach** [comment]
@mrdaniellewis Feels like we can close this now that v0.11.0 is out with a `:dialog` selector. Thanks for your thoughts and work on this!
